name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv:
          - black
          - flake8
          - mypy
          - isort
    env:
      TOXENV: ${{ matrix.toxenv }}
    
    name: "Tox ${{ matrix.toxenv }}"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        
      - name: Install Requirements [${{ matrix.toxenv }}]
        run: pip install tox
      
      - name: Tox-${{ matrix.toxenv }}
        run: tox
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv:
          - py38
          - py39
          - py310
        include:
          - toxenv: py38
            python-version: '3.8'
          - toxenv: py39
            python-version: '3.9'
          - toxenv: py310
            python-version: '3.10'
          - toxenv: py311
            python-version: '3.11'
          - toxenv: py312
            python-version: '3.12'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TOXENV: ${{ matrix.toxenv }}
    name: "Python ${{ matrix.python-version }} | Tox ${{ matrix.toxenv }}"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Install Requirements [Python-${{ matrix.python-version }}]
        run: pip install tox
      
      - name: Tox-${{ matrix.toxenv }}
        run: tox
      
      - name: Upload coverage to Codecov
        # see https://github.com/codecov/codecov-action/blob/master/README.md
        uses: codecov/codecov-action@v2
        with:
          flags: unittests-${{ matrix.python-version }}
          fail_ci_if_error: true  # default = false
          os: toxenv
          verbose: true  # default = false
